"""Native logs schema — 9 tables for chat, heartbeat prompts, daily outputs,
meetings, plugin hooks, workspace mutations, routine runs, and brain transcripts.

Creates all 9 tables in BOTH PostgreSQL and SQLite modes.  Writers are wired
in later phases (Steps 2-7); this migration only establishes the schema so that
the tables exist and FK constraints are validatable.

Revision ID: 0011
Revises: 0010
Create Date: 2026-04-26
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_pg() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _has_table(conn, name: str) -> bool:
    return inspect(conn).has_table(name)


def _has_index(conn, table: str, index_name: str) -> bool:
    existing = {idx["name"] for idx in inspect(conn).get_indexes(table)}
    return index_name in existing


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:
    conn = op.get_bind()

    # -----------------------------------------------------------------------
    # 1. agent_chat_sessions
    # -----------------------------------------------------------------------
    if not _has_table(conn, "agent_chat_sessions"):
        op.create_table(
            "agent_chat_sessions",
            sa.Column("id", sa.String(36), primary_key=True),  # UUID generated by Node
            sa.Column("agent_name", sa.String(100), nullable=False),
            sa.Column(
                "ticket_id",
                sa.String(36),
                sa.ForeignKey("tickets.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "last_activity_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        )
        op.create_index(
            "ix_agent_chat_sessions_agent",
            "agent_chat_sessions",
            ["agent_name"],
        )
        op.create_index(
            "ix_agent_chat_sessions_created",
            "agent_chat_sessions",
            ["created_at"],
        )

    # -----------------------------------------------------------------------
    # 2. agent_chat_messages
    # -----------------------------------------------------------------------
    if not _has_table(conn, "agent_chat_messages"):
        op.create_table(
            "agent_chat_messages",
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column(
                "session_id",
                sa.String(36),
                sa.ForeignKey("agent_chat_sessions.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("seq", sa.BigInteger, nullable=True),  # populated by writer (PG: BIGSERIAL via sequence)
            sa.Column("role", sa.String(20), nullable=False),
            sa.Column("text", sa.Text, nullable=True),
            sa.Column("blocks", sa.Text, nullable=True),   # JSON serialized
            sa.Column("files", sa.Text, nullable=True),    # JSON
            sa.Column(
                "ts",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column("rewound_at", sa.DateTime(timezone=True), nullable=True),
        )
        op.create_index(
            "ix_chat_msg_session_seq",
            "agent_chat_messages",
            ["session_id", "seq"],
        )
        op.create_index(
            "ix_chat_msg_created",
            "agent_chat_messages",
            ["ts"],
        )
        # Partial index (WHERE rewound_at IS NULL) — PG-only; SQLite ≥3.8 also
        # supports partial indexes, so safe to create on both.
        if not _has_index(conn, "agent_chat_messages", "ix_chat_msg_session_active"):
            op.create_index(
                "ix_chat_msg_session_active",
                "agent_chat_messages",
                ["session_id", "seq"],
                postgresql_where=sa.text("rewound_at IS NULL"),
                sqlite_where=sa.text("rewound_at IS NULL"),
            )

    # -----------------------------------------------------------------------
    # 3. heartbeat_run_prompts  (1:1 lazy load)
    # -----------------------------------------------------------------------
    if not _has_table(conn, "heartbeat_run_prompts"):
        op.create_table(
            "heartbeat_run_prompts",
            sa.Column(
                "run_id",
                sa.String(36),
                sa.ForeignKey("heartbeat_runs.run_id", ondelete="CASCADE"),
                primary_key=True,
            ),
            sa.Column("prompt_full", sa.Text, nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
        )
        op.create_index(
            "ix_hb_prompt_created",
            "heartbeat_run_prompts",
            ["created_at"],
        )

    # -----------------------------------------------------------------------
    # 4. daily_outputs
    # -----------------------------------------------------------------------
    if not _has_table(conn, "daily_outputs"):
        op.create_table(
            "daily_outputs",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("date", sa.Date, nullable=False),
            sa.Column("kind", sa.String(50), nullable=False),
            sa.Column("agent", sa.String(100), nullable=True),
            sa.Column("format", sa.String(10), nullable=False),
            sa.Column("content", sa.Text, nullable=False),
            sa.Column("metadata", sa.Text, nullable=True),    # JSON
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.CheckConstraint(
                "kind IN ('morning','eod','dashboard','email-triage','todoist-review',"
                "'weekly','memory-sync','memory-lint','health','trends','strategy',"
                "'community','licensing','social','meeting-summary','custom')",
                name="ck_daily_outputs_kind",
            ),
            sa.CheckConstraint(
                "format IN ('md','html')",
                name="ck_daily_outputs_format",
            ),
        )
        op.create_index(
            "ix_daily_outputs_date_kind",
            "daily_outputs",
            ["date", "kind"],
        )
        op.create_index(
            "ix_daily_outputs_created",
            "daily_outputs",
            ["created_at"],
        )

    # -----------------------------------------------------------------------
    # 5. meeting_transcripts
    # -----------------------------------------------------------------------
    if not _has_table(conn, "meeting_transcripts"):
        op.create_table(
            "meeting_transcripts",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("fathom_id", sa.String(200), nullable=False, unique=True),
            sa.Column("title", sa.Text, nullable=False),
            sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("duration_seconds", sa.Integer, nullable=True),
            sa.Column("attendees", sa.Text, nullable=True),       # JSON array
            sa.Column("transcript_full", sa.Text, nullable=True),
            sa.Column("summary", sa.Text, nullable=True),
            sa.Column("action_items", sa.Text, nullable=True),    # JSON
            sa.Column("raw_payload", sa.Text, nullable=True),     # JSON snapshot
            sa.Column(
                "synced_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
        )
        op.create_index(
            "ix_meeting_started",
            "meeting_transcripts",
            ["started_at"],
        )
        op.create_index(
            "ix_meeting_synced",
            "meeting_transcripts",
            ["synced_at"],
        )

    # -----------------------------------------------------------------------
    # 6. plugin_hook_runs
    # -----------------------------------------------------------------------
    if not _has_table(conn, "plugin_hook_runs"):
        op.create_table(
            "plugin_hook_runs",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("slug", sa.String(100), nullable=False),
            sa.Column("hook_name", sa.String(100), nullable=False),
            sa.Column("sha256", sa.String(64), nullable=True),
            sa.Column(
                "started_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("duration_ms", sa.Integer, nullable=True),
            sa.Column("exit_code", sa.Integer, nullable=True),
            sa.Column("stdout", sa.Text, nullable=True),         # truncated to 1 MB
            sa.Column("stderr", sa.Text, nullable=True),         # truncated to 1 MB
            sa.Column(
                "truncated",
                sa.Boolean,
                nullable=False,
                server_default=sa.false(),
            ),
            sa.Column("metadata", sa.Text, nullable=True),       # JSON
        )
        op.create_index(
            "ix_plugin_hook_slug_started",
            "plugin_hook_runs",
            ["slug", "started_at"],
        )
        # Partial index on failures
        if not _has_index(conn, "plugin_hook_runs", "ix_plugin_hook_failures"):
            op.create_index(
                "ix_plugin_hook_failures",
                "plugin_hook_runs",
                ["slug", "started_at"],
                postgresql_where=sa.text("exit_code != 0"),
                sqlite_where=sa.text("exit_code != 0"),
            )

    # -----------------------------------------------------------------------
    # 7. workspace_mutations
    # -----------------------------------------------------------------------
    if not _has_table(conn, "workspace_mutations"):
        op.create_table(
            "workspace_mutations",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column(
                "ts",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "user_id",
                sa.Integer,
                sa.ForeignKey("users.id", ondelete="SET NULL"),
                nullable=True,
            ),
            sa.Column("role", sa.String(50), nullable=True),
            sa.Column("op", sa.String(50), nullable=False),
            sa.Column("path", sa.Text, nullable=False),
            sa.Column("result", sa.String(20), nullable=False),
            sa.Column("extra", sa.Text, nullable=True),           # JSON
        )
        op.create_index(
            "ix_ws_mut_ts",
            "workspace_mutations",
            ["ts"],
        )
        op.create_index(
            "ix_ws_mut_user",
            "workspace_mutations",
            ["user_id", "ts"],
        )

    # -----------------------------------------------------------------------
    # 8. routine_runs
    # -----------------------------------------------------------------------
    if not _has_table(conn, "routine_runs"):
        op.create_table(
            "routine_runs",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column(
                "routine_id",
                sa.Integer,
                # FK only added if routine_definitions exists (PG-native; absent in SQLite)
                nullable=True,
            ),
            sa.Column("routine_slug", sa.String(100), nullable=False),
            sa.Column(
                "started_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("duration_ms", sa.Integer, nullable=True),
            sa.Column("exit_code", sa.Integer, nullable=True),
            sa.Column("stdout", sa.Text, nullable=True),          # truncated to 1 MB
            sa.Column("stderr", sa.Text, nullable=True),
            sa.Column(
                "truncated",
                sa.Boolean,
                nullable=False,
                server_default=sa.false(),
            ),
            sa.Column("triggered_by", sa.String(20), nullable=False, server_default="scheduler"),
            sa.Column("metadata", sa.Text, nullable=True),
        )
        op.create_index(
            "ix_routine_run_slug_started",
            "routine_runs",
            ["routine_slug", "started_at"],
        )
        # Partial index on failures
        if not _has_index(conn, "routine_runs", "ix_routine_run_failures"):
            op.create_index(
                "ix_routine_run_failures",
                "routine_runs",
                ["started_at"],
                postgresql_where=sa.text("exit_code != 0"),
                sqlite_where=sa.text("exit_code != 0"),
            )
        # Add FK to routine_definitions only if that table exists
        # (it is created by 0007 PG-only; absent in SQLite mode)
        if _has_table(conn, "routine_definitions"):
            try:
                op.create_foreign_key(
                    "fk_routine_runs_routine_id",
                    "routine_runs", "routine_definitions",
                    ["routine_id"], ["id"],
                    ondelete="SET NULL",
                )
            except Exception:
                pass  # FK may already exist; non-fatal

    # -----------------------------------------------------------------------
    # 9. brain_repo_transcripts
    # -----------------------------------------------------------------------
    if not _has_table(conn, "brain_repo_transcripts"):
        op.create_table(
            "brain_repo_transcripts",
            sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
            sa.Column("project_slug", sa.String(200), nullable=False),
            sa.Column("session_id", sa.String(200), nullable=False),
            sa.Column("source_path", sa.Text, nullable=True),
            sa.Column("content", sa.Text, nullable=False),
            sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "mirrored_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.UniqueConstraint("project_slug", "session_id", name="uq_brain_repo_project_session"),
        )
        op.create_index(
            "ix_brain_mirrored",
            "brain_repo_transcripts",
            ["mirrored_at"],
        )


# ---------------------------------------------------------------------------
# downgrade — drop in reverse FK dependency order
# ---------------------------------------------------------------------------

def downgrade() -> None:
    conn = op.get_bind()

    # No FK dependencies on these tables from the new set
    if _has_table(conn, "brain_repo_transcripts"):
        op.drop_index("ix_brain_mirrored", table_name="brain_repo_transcripts")
        op.drop_table("brain_repo_transcripts")

    if _has_table(conn, "routine_runs"):
        if _has_index(conn, "routine_runs", "ix_routine_run_failures"):
            op.drop_index("ix_routine_run_failures", table_name="routine_runs")
        op.drop_index("ix_routine_run_slug_started", table_name="routine_runs")
        op.drop_table("routine_runs")

    if _has_table(conn, "workspace_mutations"):
        op.drop_index("ix_ws_mut_user", table_name="workspace_mutations")
        op.drop_index("ix_ws_mut_ts", table_name="workspace_mutations")
        op.drop_table("workspace_mutations")

    if _has_table(conn, "plugin_hook_runs"):
        if _has_index(conn, "plugin_hook_runs", "ix_plugin_hook_failures"):
            op.drop_index("ix_plugin_hook_failures", table_name="plugin_hook_runs")
        op.drop_index("ix_plugin_hook_slug_started", table_name="plugin_hook_runs")
        op.drop_table("plugin_hook_runs")

    if _has_table(conn, "meeting_transcripts"):
        op.drop_index("ix_meeting_synced", table_name="meeting_transcripts")
        op.drop_index("ix_meeting_started", table_name="meeting_transcripts")
        op.drop_table("meeting_transcripts")

    if _has_table(conn, "daily_outputs"):
        op.drop_index("ix_daily_outputs_created", table_name="daily_outputs")
        op.drop_index("ix_daily_outputs_date_kind", table_name="daily_outputs")
        op.drop_table("daily_outputs")

    if _has_table(conn, "heartbeat_run_prompts"):
        op.drop_index("ix_hb_prompt_created", table_name="heartbeat_run_prompts")
        op.drop_table("heartbeat_run_prompts")

    # agent_chat_messages before agent_chat_sessions (CASCADE FK)
    if _has_table(conn, "agent_chat_messages"):
        if _has_index(conn, "agent_chat_messages", "ix_chat_msg_session_active"):
            op.drop_index("ix_chat_msg_session_active", table_name="agent_chat_messages")
        op.drop_index("ix_chat_msg_created", table_name="agent_chat_messages")
        op.drop_index("ix_chat_msg_session_seq", table_name="agent_chat_messages")
        op.drop_table("agent_chat_messages")

    if _has_table(conn, "agent_chat_sessions"):
        op.drop_index("ix_agent_chat_sessions_created", table_name="agent_chat_sessions")
        op.drop_index("ix_agent_chat_sessions_agent", table_name="agent_chat_sessions")
        op.drop_table("agent_chat_sessions")
